name: reagent_colors_test
description: "A reagent testing app with Firebase integration."
publish_to: 'none'
version: 1.0.0+25

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Internationalization
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  google_sign_in: ^6.3.0
  go_router: ^16.2.1
  responsive_framework: ^1.5.1
  data_table_2: ^2.6.0
  flutter_form_builder: ^10.1.0
  url_launcher: ^6.3.2
  fl_chart: ^1.1.0
  icons_plus: ^5.0.0
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/data/
