// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlVzXltjyUnU-F6jKcAB6C_OBHL9iFTRA',
    appId: '1:76342007759:web:ec5cd1f83580a0fb3164ba',
    messagingSenderId: '76342007759',
    projectId: 'flutter-reagent-test',
    authDomain: 'flutter-reagent-test.firebaseapp.com',
    storageBucket: 'flutter-reagent-test.firebasestorage.app',
    measurementId: 'G-8CPPS6G70D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACZoxTtCY8TLEljnl2fI_vI9zlDHRwgHI',
    appId: '1:76342007759:android:1d8bec4e1e5955d43164ba',
    messagingSenderId: '76342007759',
    projectId: 'flutter-reagent-test',
    storageBucket: 'flutter-reagent-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpek992tVFKJe4OK5eLSvj1bAGqrl5Lmw',
    appId: '1:76342007759:ios:585b35dec8e2e35b3164ba',
    messagingSenderId: '76342007759',
    projectId: 'flutter-reagent-test',
    storageBucket: 'flutter-reagent-test.firebasestorage.app',
    iosClientId: '76342007759-lfrim4jh8fkntca1o7mlsvldaaqbomaa.apps.googleusercontent.com',
    iosBundleId: 'com.example.reagentColorsTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpek992tVFKJe4OK5eLSvj1bAGqrl5Lmw',
    appId: '1:76342007759:ios:585b35dec8e2e35b3164ba',
    messagingSenderId: '76342007759',
    projectId: 'flutter-reagent-test',
    storageBucket: 'flutter-reagent-test.firebasestorage.app',
    iosClientId: '76342007759-lfrim4jh8fkntca1o7mlsvldaaqbomaa.apps.googleusercontent.com',
    iosBundleId: 'com.example.reagentColorsTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlVzXltjyUnU-F6jKcAB6C_OBHL9iFTRA',
    appId: '1:76342007759:web:0318c3f7a6adef6e3164ba',
    messagingSenderId: '76342007759',
    projectId: 'flutter-reagent-test',
    authDomain: 'flutter-reagent-test.firebaseapp.com',
    storageBucket: 'flutter-reagent-test.firebasestorage.app',
    measurementId: 'G-VHXK936Q4Z',
  );

}