// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi0auWjmzx0aRk4JizKQPZlt2UEVLBS0k',
    appId: '1:664679183291:web:b3a295407d35547cef8a9e',
    messagingSenderId: '664679183291',
    projectId: 'flut-reagent',
    authDomain: 'flut-reagent.firebaseapp.com',
    storageBucket: 'flut-reagent.firebasestorage.app',
    measurementId: 'G-9DPFC24ZYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACEfpp4AwjuvQr68sUu0ZhupcPYTsWvzI',
    appId: '1:664679183291:android:9124746a8fc517c1ef8a9e',
    messagingSenderId: '664679183291',
    projectId: 'flut-reagent',
    storageBucket: 'flut-reagent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWbDUGLiLVolihpBjHFd6HRgFgOOpKFiA',
    appId: '1:664679183291:ios:8c329d7a513e0b68ef8a9e',
    messagingSenderId: '664679183291',
    projectId: 'flut-reagent',
    storageBucket: 'flut-reagent.firebasestorage.app',
    iosClientId: '664679183291-037ccq2lqr4l76omp5kelrsc9g0rpcql.apps.googleusercontent.com',
    iosBundleId: 'com.example.reagentColorsTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWbDUGLiLVolihpBjHFd6HRgFgOOpKFiA',
    appId: '1:664679183291:ios:8c329d7a513e0b68ef8a9e',
    messagingSenderId: '664679183291',
    projectId: 'flut-reagent',
    storageBucket: 'flut-reagent.firebasestorage.app',
    iosClientId: '664679183291-037ccq2lqr4l76omp5kelrsc9g0rpcql.apps.googleusercontent.com',
    iosBundleId: 'com.example.reagentColorsTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi0auWjmzx0aRk4JizKQPZlt2UEVLBS0k',
    appId: '1:664679183291:web:336d33e2fdc631f0ef8a9e',
    messagingSenderId: '664679183291',
    projectId: 'flut-reagent',
    authDomain: 'flut-reagent.firebaseapp.com',
    storageBucket: 'flut-reagent.firebasestorage.app',
    measurementId: 'G-FW9ME05SZY',
  );
}
